Fixes #18761: Add solaris to 6.2 release data
Normation/rudder-tools pull request #651
Opened 2020-12-10 16:46 UTC by peckpeck

https://issues.rudder.io/issues/18761

2020-12-10 16:47 UTC, VinceMacBuche approved these changes

2020-12-10 16:48 UTC, VinceMacBuche requested changes

2020-12-10 16:48 UTC, VinceMacBuche commented on release-data/rudder-6.1.cson
> +                  "armbian-8":      [ "armhf" ],
WHy keeping armhf here  and not in https://github.com/Normation/rudder-tools/pull/651/files#diff-c4e06da963cd3b736367273f7c9c7615f9688801abeca66117b3b0fea7698ca2L16 ?

2020-12-10 16:48 UTC, VinceMacBuche commented on release-data/rudder-6.0.cson
> +                  "armbian-8":      [ "armhf" ],
Same here

2020-12-10 16:53 UTC, peckpeck commented on release-data/rudder-6.1.cson
> +                  "armbian-8":      [ "armhf" ],
because armhf was built on 6.0 and 6.1

2020-12-10 17:04 UTC, VinceMacBuche commented on release-data/rudder-6.1.cson
> +                  "armbian-8":      [ "armhf" ],
was built, but is not anymore ?

2020-12-11 13:52 UTC, peckpeck commented on release-data/rudder-6.1.cson
> +                  "armbian-8":      [ "armhf" ],
not anymore on 6.0 since most 6.0 tasks have been disabled

2021-01-14 09:04 UTC, VinceMacBuche approved these changes

2021-01-14 09:07 UTC, Normation-Quality-Assistant commented
OK, merging this PR

2021-01-14 09:07 UTC, merged